import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./components/common/Navbar";
import TanstackProvider from "./components/providers/TanstackProvider";
import Footer from "./components/common/Footer";
import Header from "./components/common/Header";
import { ToastContainer } from "react-toastify";
import Notification from "./components/notification/Notification";
import { Suspense } from "react";
import Load from "./loading";
import { StoreProvider } from "./store/StoreProvider";
import Inner from "./components/Inner";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abissinia Tickets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" data-theme="black">
        <TanstackProvider>
          <body className={inter.className}>
            <NextTopLoader
              color="#2299DD"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              showSpinner={true}
              easing="ease"
              speed={200}
              shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            />
            <Header />
            <Navbar />
            <Notification />
            <ToastContainer />
            <Suspense fallback={<Load />}>
              <Inner>{children}</Inner>
              <Footer />
            </Suspense>
          </body>
        </TanstackProvider>
      </html>
    </StoreProvider>
  );
}
