import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./components/Navbar";
import TanstackProvider from "./components/providers/TanstackProvider";
import Footer from "./components/Footer";
import { AppProvider, useGlobalContext } from "./context";
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";
import Notification from "./components/Notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abissinia Tickets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="black">
      <AppProvider>
        <TanstackProvider>
          <body className={inter.className}>
            <Header />
            <Navbar />
            <Notification />
            <ToastContainer />
            <main>{children}</main>
            <Footer />
          </body>
        </TanstackProvider>
      </AppProvider>
    </html>
  );
}
